from __future__ import annotations

import json
from pathlib import Path

from .schema import OptionMeta, SchemaCatalog


RESOURCE_ROOT = Path(__file__).resolve().parent / "resources"
LEGACY_ROOT = RESOURCE_ROOT / "legacy"
GENERATED_ROOT = RESOURCE_ROOT / "generated"


class RuntimeSchemaCatalog(SchemaCatalog):
    """Schema catalog used by the desktop editor.

    The old INI resources are source material. Normal runtime lookups prefer the
    compiled JSON generated by tools/build_rule_resources.py so labels/help/types are
    fast, deterministic and shared by YR and Ares.
    """

    def __init__(self) -> None:
        super().__init__(LEGACY_ROOT if LEGACY_ROOT.exists() else None)
        self._load_generated()

    def _load_generated(self) -> None:
        schema_path = GENERATED_ROOT / "rules_schema.json"
        if schema_path.exists():
            try:
                payload = json.loads(schema_path.read_text("utf-8"))
            except Exception:
                payload = {}
            for key, row in payload.get("options", {}).items():
                old = self.options.get(key)
                values = tuple(
                    (str(item.get("value", "")), str(item.get("label") or item.get("value", "")))
                    for item in row.get("values", [])
                )
                self.options[key] = OptionMeta(
                    name=key,
                    description=str(row.get("description", old.description if old else "")),
                    help_text=str(row.get("help", old.help_text if old else "")),
                    category=str(row.get("category", old.category if old else "特殊")),
                    source=str(row.get("source", old.source if old else "YR")),
                    values=values or (old.values if old else ()),
                    value_type=str(row.get("value_type", old.value_type if old else "text")),
                    applies_to=tuple(row.get("applies_to", old.applies_to if old else ())),
                    default=str(row.get("default", old.default if old else "")),
                    docs=str(row.get("docs", old.docs if old else "")),
                )

        names_path = GENERATED_ROOT / "section_names.json"
        if names_path.exists():
            try:
                names = json.loads(names_path.read_text("utf-8"))
            except Exception:
                names = {}
            if isinstance(names, dict):
                self.name_desc.update({str(key): str(value) for key, value in names.items()})
